platform :android do
  lane :deploy do
    upload_to_play_store(
      track: "production",
      aab: "app/build/outputs/bundle/productionRelease/app-production-release.aab",
      json_key: ENV["GPLAY_SERVICE_ACCOUNT_KEY"],
      package_name: ENV["PACKAGE_NAME"],
      skip_upload_metadata: true,
      skip_upload_changelogs: false,
      skip_upload_images: true,
      skip_upload_screenshots: true
    )
  end
end